-- 0022_certificate_identity_photo.sql
-- Certificate redesign support:
--  - candidate_code: a short, unique, system-generated ID per candidate account,
--    stable across all of that candidate's certificates, printed as "Candidate
--    ID". Generated by the app (service role) on first certificate issuance.
--  - certificate_photo_path / _status: an OPTIONAL photo the candidate uploads
--    for their certificate (separate from the ID-check selfie). Only an
--    admin-APPROVED photo is embedded on generated certificates.
--  - a private bucket for those photos.

alter table public.profiles
  add column if not exists candidate_code           text,
  add column if not exists certificate_photo_path   text,
  add column if not exists certificate_photo_status text; -- null | 'pending' | 'approved' | 'rejected'

-- The candidate code is unique across accounts.
create unique index if not exists profiles_candidate_code_key
  on public.profiles (candidate_code)
  where candidate_code is not null;

alter table public.profiles
  drop constraint if exists profiles_cert_photo_status_chk;
alter table public.profiles
  add constraint profiles_cert_photo_status_chk
  check (certificate_photo_status is null
         or certificate_photo_status in ('pending', 'approved', 'rejected'));

-- Candidates may set their own certificate photo PATH (upload); the code and the
-- approval status are set by the app via the service role only.
grant update (certificate_photo_path) on public.profiles to authenticated;

-- ---------------------------------------------------------------------------
-- Private bucket for certificate photos. Own-path RLS (first segment = user id).
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('certificate-photos', 'certificate-photos', false)
on conflict (id) do nothing;

drop policy if exists "cert_photos_insert_own" on storage.objects;
create policy "cert_photos_insert_own"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'certificate-photos'
              and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "cert_photos_update_own" on storage.objects;
create policy "cert_photos_update_own"
  on storage.objects for update to authenticated
  using (bucket_id = 'certificate-photos'
         and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "cert_photos_read_own" on storage.objects;
create policy "cert_photos_read_own"
  on storage.objects for select to authenticated
  using (bucket_id = 'certificate-photos'
         and (storage.foldername(name))[1] = auth.uid()::text);

-- Admins read photos for approval via the service role (bypasses RLS).
